<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
* @var yii\web\View $this
* @var app\models\ProgramaHasTipoRecurso $model
* @var yii\widgets\ActiveForm $form
*/

?>

<div class="programa-has-tipo-recurso-form">

    <?php $form = ActiveForm::begin([
    'id' => 'ProgramaHasTipoRecurso',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-danger',
    'fieldConfig' => [
             'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
             'horizontalCssClasses' => [
                 'label' => 'col-sm-2',
                 #'offset' => 'col-sm-offset-4',
                 'wrapper' => 'col-sm-8',
                 'error' => '',
                 'hint' => '',
             ],
         ],
    ]
    );
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>
            

            <!-- attribute programaid -->
<?= 
    // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
    $form->field($model, 'programaid')->dropDownList(
        \yii\helpers\ArrayHelper::map(app\models\Programa::find()->all(), 'id', 'nombre'),
        [
            'prompt' => 'Select',
            'disabled' => (isset($relAttributes) && isset($relAttributes['programaid'])),
        ]
    ); 
?>
            
<!-- attribute tipo_recursoid -->
<?= 
    // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
    $form->field($model, 'tipo_recursoid')->dropDownList(
        \yii\helpers\ArrayHelper::map(app\models\TipoRecurso::find()->all(), 'id', 'nombre'),
        [
            'prompt' => 'Select',
            'disabled' => (isset($relAttributes) && isset($relAttributes['tipo_recursoid'])),
        ]
    ); 
?>


        </p>
        <?php $this->endBlock(); ?>
        
        <?=
    Tabs::widget(
                 [
                    'encodeLabels' => false,
                    'items' => [ 
                        [
    'label'   => Yii::t('models', 'ProgramaHasTipoRecurso'),
    'content' => $this->blocks['main'],
    'active'  => true,
],
                    ]
                 ]
    );
    ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
        '<span class="glyphicon glyphicon-check"></span> ' .
        ($model->isNewRecord ? 'Create' : 'Save'),
        [
        'id' => 'save-' . $model->formName(),
        'class' => 'btn btn-success'
        ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>

