<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
* @var yii\web\View $this
* @var app\models\ProgramaHasTipoRecurso $model
*/
$copyParams = $model->attributes;

$this->title = Yii::t('models', 'Programa Has Tipo Recurso');
$this->params['breadcrumbs'][] = ['label' => Yii::t('models', 'Programa Has Tipo Recursos'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->programa->nombre, 'url' => ['view', 'tipo_recursoid' => $model->tipo_recursoid, 'programaid' => $model->programaid]];
$this->params['breadcrumbs'][] = 'View';
?>
<div class="giiant-crud programa-has-tipo-recurso-view">

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <h1>
        <?= Yii::t('models', 'Programa Has Tipo Recurso') ?>
        <small>
            <?= Html::encode($model->tipo_recursoid) ?>
        </small>
    </h1>


    <div class="clearfix crud-navigation">

        <!-- menu buttons -->
        <div class='pull-left'>
            <?= Html::a(
            '<span class="glyphicon glyphicon-pencil"></span> ' . 'Editar',
            [ 'update', 'tipo_recursoid' => $model->tipo_recursoid, 'programaid' => $model->programaid],
            ['class' => 'btn btn-info']) ?>

            <?= Html::a(
            '<span class="glyphicon glyphicon-copy"></span> ' . 'Copiar',
            ['create', 'tipo_recursoid' => $model->tipo_recursoid, 'programaid' => $model->programaid, 'ProgramaHasTipoRecurso'=>$copyParams],
            ['class' => 'btn btn-success']) ?>

            <?= Html::a(
            '<span class="glyphicon glyphicon-plus"></span> ' . 'Nuevo',
            ['create'],
            ['class' => 'btn btn-success']) ?>
        </div>

        <div class="pull-right">
            <?= Html::a('<span class="glyphicon glyphicon-list"></span> '
            . 'Full list', ['index'], ['class'=>'btn btn-default']) ?>
        </div>

    </div>

    <hr/>

    <?php $this->beginBlock('app\models\ProgramaHasTipoRecurso'); ?>

    
    <?= DetailView::widget([
    'model' => $model,
    'attributes' => [
    // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'tipo_recursoid',
    'value' => ($model->tipoRecurso ? 
        Html::a('<i class="glyphicon glyphicon-list"></i>', ['tipo-recurso/index']).' '.
        Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->tipoRecurso->nombre, ['tipo-recurso/view', 'id' => $model->tipoRecurso->id,]).' '.
        Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'ProgramaHasTipoRecurso'=>['tipo_recursoid' => $model->tipo_recursoid]])
        : 
        '<span class="label label-warning">?</span>'),
],
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'programaid',
    'value' => ($model->programa ? 
        Html::a('<i class="glyphicon glyphicon-list"></i>', ['programa/index']).' '.
        Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->programa->nombre, ['programa/view', 'id' => $model->programa->id,]).' '.
        Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'ProgramaHasTipoRecurso'=>['programaid' => $model->programaid]])
        : 
        '<span class="label label-warning">?</span>'),
],
    ],
    ]); ?>

    
    <hr/>

    <?= Html::a('<span class="glyphicon glyphicon-trash"></span> ' . 'Delete', ['delete', 'tipo_recursoid' => $model->tipo_recursoid, 'programaid' => $model->programaid],
    [
    'class' => 'btn btn-danger',
    'data-confirm' => '' . 'Are you sure to delete this item?' . '',
    'data-method' => 'post',
    ]); ?>
    <?php $this->endBlock(); ?>


    
    <?= Tabs::widget(
                 [
                     'id' => 'relation-tabs',
                     'encodeLabels' => false,
                     'items' => [
 [
    'label'   => '<b class=""># '.Html::encode($model->tipo_recursoid).'</b>',
    'content' => $this->blocks['app\models\ProgramaHasTipoRecurso'],
    'active'  => true,
],
 ]
                 ]
    );
    ?>
</div>
