<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\modules\backend\controllers\base;

use app\models\TipoRecursoHasPrograma;
use yii\web\Controller;
use yii\web\HttpException;
use yii\helpers\Url;
use yii\filters\AccessControl;
use dmstr\bootstrap\Tabs;

/**
* TipoRecursoHasProgramaController implements the CRUD actions for TipoRecursoHasPrograma model.
*/
class TipoRecursoHasProgramaController extends Controller
{


/**
* @var boolean whether to enable CSRF validation for the actions in this controller.
* CSRF validation is enabled only when both this property and [[Request::enableCsrfValidation]] are true.
*/
public $enableCsrfValidation = false;


/**
* Lists all TipoRecursoHasPrograma models.
* @return mixed
*/
public function actionIndex()
{
    $dataProvider = new \yii\data\ActiveDataProvider([
    'query' => TipoRecursoHasPrograma::find(),
    ]);

Tabs::clearLocalStorage();

Url::remember();
\Yii::$app->session['__crudReturnUrl'] = null;

return $this->render('index', [
'dataProvider' => $dataProvider,
]);
}

/**
* Displays a single TipoRecursoHasPrograma model.
* @param integer $tipo_recursoid
	 * @param integer $programaid
*
* @return mixed
*/
public function actionView($tipo_recursoid, $programaid)
{
\Yii::$app->session['__crudReturnUrl'] = Url::previous();
Url::remember();
Tabs::rememberActiveState();

return $this->render('view', [
'model' => $this->findModel($tipo_recursoid, $programaid),
]);
}

/**
* Creates a new TipoRecursoHasPrograma model.
* If creation is successful, the browser will be redirected to the 'view' page.
* @return mixed
*/
public function actionCreate()
{
$model = new TipoRecursoHasPrograma;

try {
if ($model->load($_POST) && $model->save()) {
return $this->redirect(['view', 'tipo_recursoid' => $model->tipo_recursoid, 'programaid' => $model->programaid]);
} elseif (!\Yii::$app->request->isPost) {
$model->load($_GET);
}
} catch (\Exception $e) {
$msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
$model->addError('_exception', $msg);
}
return $this->render('create', ['model' => $model]);
}

/**
* Updates an existing TipoRecursoHasPrograma model.
* If update is successful, the browser will be redirected to the 'view' page.
* @param integer $tipo_recursoid
	 * @param integer $programaid
* @return mixed
*/
public function actionUpdate($tipo_recursoid, $programaid)
{
$model = $this->findModel($tipo_recursoid, $programaid);

if ($model->load($_POST) && $model->save()) {
return $this->redirect(Url::previous());
} else {
return $this->render('update', [
'model' => $model,
]);
}
}

/**
* Deletes an existing TipoRecursoHasPrograma model.
* If deletion is successful, the browser will be redirected to the 'index' page.
* @param integer $tipo_recursoid
	 * @param integer $programaid
* @return mixed
*/
public function actionDelete($tipo_recursoid, $programaid)
{
try {
$this->findModel($tipo_recursoid, $programaid)->delete();
} catch (\Exception $e) {
$msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
\Yii::$app->getSession()->addFlash('error', $msg);
return $this->redirect(Url::previous());
}

// TODO: improve detection
$isPivot = strstr('$tipo_recursoid, $programaid',',');
if ($isPivot == true) {
return $this->redirect(Url::previous());
} elseif (isset(\Yii::$app->session['__crudReturnUrl']) && \Yii::$app->session['__crudReturnUrl'] != '/') {
Url::remember(null);
$url = \Yii::$app->session['__crudReturnUrl'];
\Yii::$app->session['__crudReturnUrl'] = null;

return $this->redirect($url);
} else {
return $this->redirect(['index']);
}
}

/**
* Finds the TipoRecursoHasPrograma model based on its primary key value.
* If the model is not found, a 404 HTTP exception will be thrown.
* @param integer $tipo_recursoid
	 * @param integer $programaid
* @return TipoRecursoHasPrograma the loaded model
* @throws HttpException if the model cannot be found
*/
protected function findModel($tipo_recursoid, $programaid)
{
if (($model = TipoRecursoHasPrograma::findOne(['tipo_recursoid' => $tipo_recursoid, 'programaid' => $programaid])) !== null) {
return $model;
} else {
throw new HttpException(404, 'The requested page does not exist.');
}
}
}
