<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "programa".
 *
 * @property integer $id
 * @property string $nombre
 * @property integer $activo
 * @property string $color
 *
 * @property \app\models\ProgramaHasTipoRecurso[] $programaHasTipoRecursos
 * @property \app\models\TipoRecurso[] $tipoRecursos
 * @property \app\models\Recurso[] $recursos
 * @property string $aliasModel
 */
abstract class Programa extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'programa';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['activo'], 'integer'],
            [['color'], 'required'],
            [['nombre'], 'string', 'max' => 200],
            [['color'], 'string', 'max' => 15]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nombre' => 'Nombre',
            'activo' => 'Activo',
            'color' => 'Color',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProgramaHasTipoRecursos()
    {
        return $this->hasMany(\app\models\ProgramaHasTipoRecurso::className(), ['programaid' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTipoRecursos()
    {
        return $this->hasMany(\app\models\TipoRecurso::className(), ['id' => 'tipo_recursoid'])->viaTable('programa_has_tipo_recurso', ['programaid' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRecursos()
    {
        return $this->hasMany(\app\models\Recurso::className(), ['programaid' => 'id']);
    }




}
