<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "programa_has_usuario".
 *
 * @property integer $id
 * @property integer $userid
 * @property integer $programaid
 * @property string $permiso
 * @property string $create_at
 *
 * @property \app\models\Programa $programa
 * @property \app\models\User $user
 * @property string $aliasModel
 */
abstract class ProgramaHasUsuario extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'programa_has_usuario';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['userid', 'programaid'], 'integer'],
            [['create_at'], 'safe'],
            [['permiso'], 'string', 'max' => 64],
            [['programaid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Programa::className(), 'targetAttribute' => ['programaid' => 'id']],
            [['userid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['userid' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'userid' => 'Userid',
            'programaid' => 'Programaid',
            'permiso' => 'Permiso',
            'create_at' => 'Create At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPrograma()
    {
        return $this->hasOne(\app\models\Programa::className(), ['id' => 'programaid']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'userid']);
    }




}
