<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "recurso".
 *
 * @property integer $id
 * @property string $fecha_inicial
 * @property string $fecha_alta
 * @property double $monto
 * @property string $observacion
 * @property string $proposito
 * @property integer $programaid
 * @property integer $tipo_recursoid
 * @property integer $personaid
 * @property string $fecha_baja
 * @property string $fecha_acreditacion
 * @property string $descripcion_baja
 * @property integer $localidadid
 *
 * @property \app\models\Aula[] $aulas
 * @property \app\models\Programa $programa
 * @property \app\models\TipoRecurso $tipoRecurso
 * @property string $aliasModel
 */
abstract class Recurso extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'recurso';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['fecha_inicial', 'fecha_alta', 'monto', 'programaid', 'tipo_recursoid', 'personaid'], 'required'],
            [['fecha_inicial', 'fecha_alta', 'fecha_baja', 'fecha_acreditacion'], 'safe'],
            [['monto'], 'number'],
            [['observacion', 'proposito', 'descripcion_baja'], 'string'],
            [['programaid', 'tipo_recursoid', 'personaid', 'localidadid'], 'integer'],
            [['programaid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Programa::className(), 'targetAttribute' => ['programaid' => 'id']],
            [['tipo_recursoid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\TipoRecurso::className(), 'targetAttribute' => ['tipo_recursoid' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'fecha_inicial' => 'Fecha Inicial',
            'fecha_alta' => 'Fecha Alta',
            'monto' => 'Monto',
            'observacion' => 'Observacion',
            'proposito' => 'Proposito',
            'programaid' => 'Programaid',
            'tipo_recursoid' => 'Tipo Recursoid',
            'personaid' => 'Personaid',
            'fecha_baja' => 'Fecha Baja',
            'fecha_acreditacion' => 'Fecha Acreditacion',
            'descripcion_baja' => 'Descripcion Baja',
            'localidadid' => 'Localidadid',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'observacion' => '
',
            'personaid' => 'Este atributo hace referencia a una persona del sistema Registral',
            'localidadid' => 'Este atributo hace referencia al sistema Lugar (interoperabilidad)',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAulas()
    {
        return $this->hasMany(\app\models\Aula::className(), ['recursoid' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPrograma()
    {
        return $this->hasOne(\app\models\Programa::className(), ['id' => 'programaid']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTipoRecurso()
    {
        return $this->hasOne(\app\models\TipoRecurso::className(), ['id' => 'tipo_recursoid']);
    }




}
