<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "responsable_entrega".
 *
 * @property integer $tipo_responsableid
 * @property integer $recursoid
 * @property integer $responsable_entregaid
 *
 * @property \app\models\Recurso $recurso
 * @property \app\models\TipoResponsable $tipoResponsable
 * @property string $aliasModel
 */
abstract class ResponsableEntrega extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'responsable_entrega';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['tipo_responsableid'], 'required'],
            [['tipo_responsableid', 'responsable_entregaid'], 'integer'],
            [['recursoid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Recurso::className(), 'targetAttribute' => ['recursoid' => 'id']],
            [['tipo_responsableid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\TipoResponsable::className(), 'targetAttribute' => ['tipo_responsableid' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'tipo_responsableid' => 'Tipo Responsableid',
            'recursoid' => 'Recursoid',
            'responsable_entregaid' => 'Responsable Entregaid',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'tipo_responsableid' => 'esto nos permite tener multiples tipos de responsables. ej municipio, delegacion, comision de fomente,etc',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRecurso()
    {
        return $this->hasOne(\app\models\Recurso::className(), ['id' => 'recursoid']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTipoResponsable()
    {
        return $this->hasOne(\app\models\TipoResponsable::className(), ['id' => 'tipo_responsableid']);
    }




}
