<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "tipo_recurso".
 *
 * @property integer $id
 * @property string $nombre
 *
 * @property \app\models\ProgramaHasTipoRecurso[] $programaHasTipoRecursos
 * @property \app\models\Programa[] $programas
 * @property \app\models\Recurso[] $recursos
 * @property string $aliasModel
 */
abstract class TipoRecurso extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tipo_recurso';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nombre'], 'string', 'max' => 200]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nombre' => 'Nombre',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProgramaHasTipoRecursos()
    {
        return $this->hasMany(\app\models\ProgramaHasTipoRecurso::className(), ['tipo_recursoid' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProgramas()
    {
        return $this->hasMany(\app\models\Programa::className(), ['id' => 'programaid'])->viaTable('programa_has_tipo_recurso', ['tipo_recursoid' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRecursos()
    {
        return $this->hasMany(\app\models\Recurso::className(), ['tipo_recursoid' => 'id']);
    }




}
