<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "user_persona".
 *
 * @property integer $userid
 * @property integer $personaid
 * @property integer $localidadid
 * @property string $fecha_baja
 * @property string $descripcion_baja
 * @property string $last_login_ip
 *
 * @property \app\models\User $user
 * @property string $aliasModel
 */
abstract class UserPersona extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user_persona';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['personaid', 'localidadid'], 'required'],
            [['personaid', 'localidadid'], 'integer'],
            [['fecha_baja'], 'safe'],
            [['descripcion_baja'], 'string'],
            [['last_login_ip'], 'string', 'max' => 20],
            [['userid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['userid' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'userid' => 'Userid',
            'personaid' => 'Personaid',
            'localidadid' => 'Localidadid',
            'fecha_baja' => 'Fecha Baja',
            'descripcion_baja' => 'Descripcion Baja',
            'last_login_ip' => 'Last Login Ip',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'userid']);
    }




}
